#cloud-config

package_update: true

packages: ['docker']

runcmd:
  # create docker network
  - docker network create wordpress-tier

  # create and run mariadb
  - docker volume create --name mariadb_data  
  - docker run -d --name mariadb
    -e ALLOW_EMPTY_PASSWORD=yes
    -e MARIADB_USER=bn_wordpress
    -e MARIADB_DATABASE=bitnami_wordpress
    --net wordpress-tier
    --volume mariadb_data:/bitnami
    --log-driver=awslogs
    --log-opt awslogs-region=eu-central-1
    --log-opt awslogs-group=cafe-grundeinkommen
    bitnami/mariadb:latest

  # create and run wordpress
  - docker volume create --name wordpress_data
  - docker run -d --name wordpress -p 80:80 -p 443:443
    -e ALLOW_EMPTY_PASSWORD=yes
    -e WORDPRESS_DATABASE_USER=bn_wordpress
    -e WORDPRESS_DATABASE_NAME=bitnami_wordpress
    --net wordpress-tier
    --volume wordpress_data:/bitnami
    --log-driver=awslogs
    --log-opt awslogs-region=eu-central-1
    --log-opt awslogs-group=cafe-grundeinkommen
    bitnami/wordpress:latest