version: 0.2

phases:
  pre_build:
    commands:
      - pip install awscli --upgrade --user
      - echo `aws --version`
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region ${region} --no-include-email)
      - REPOSITORY_URI=${repository_url}
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ${image_name}:latest .
      - docker tag ${image_name}:latest ${image_name}:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push ${image_name}:latest
      - docker push ${image_name}:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"${image_name}","imageUri":"%s"}]' ${image_name}:$IMAGE_TAG > imagedefinitions.json      
artifacts:
  files: imagedefinitions.json
