version: 0.2

phases:
  pre_build:
    commands:     
      - echo Entered the pre_build phase...  
      - API_VERSION="v$( node -p "require('./package.json').version" )"
      - export API_VERSION
      - echo Installing node packages ...      
      - npm install
      - echo Installing and compiling contracts ...
      - mkdir contracts
      - cd contracts
      - npm install -g ganache-cli
      - nohup ganache-cli -i 5777 &
      - git clone https://github.com/CirclesUBI/circles-contracts.git .
      - npm install
      - npm install websocket
      - npx truffle compile
      - npx truffle migrate
      - cd ..
  build:
    commands:
      - echo Build started on `date`
      - echo Starting migrations ...    
      - npm run migrate:up
      - echo Starting tests ...
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo cleaning up ...
      - rm -rf node_modules
      - (echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) > image_tag.txt
artifacts:
  files: '**/*'
