version: 0.2

phases:
  pre_build:
    commands:       
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ${region} --no-include-email)
      - IMAGE_TAG=`cat image_tag.txt`
      - REPOSITORY_URI=${repository_url}
      - echo REPOSITORY_URI $REPOSITORY_URI
      - echo IMAGE_TAG $IMAGE_TAG
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"circles-api-ecr","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json      
artifacts:
  files: imagedefinitions.json
