version: 0.2

phases:
  pre_build:
    commands:      
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd ${lambda_function_name}
      - zip ../index.zip index.js  
  post_build:
    commands:
      - echo Build completed on `date`      
artifacts:
  files: index.zip