#cloud-config

package_update: false

packages: ['unzip', 'wget']

users:
  - default

write_files:
  - path: /cloudwatch.json
    permissions: '0644'
    encoding: base64
    content: ${base64encode(cloudwatch_json)}

runcmd:
  # set up logging
  - wget https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip
  - unzip AmazonCloudWatchAgent.zip
  - ./install.sh
  - /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/cloudwatch.json -s
  
  # Install docker
  - apt install docker.io -y

  # Install mongo and backup  etc
  - snap install mongo33
  - mongo33.d --bind_ip 0.0.0.0
  - MY_IP=$(ip route get 8.8.8.8| grep src| sed 's/.*src \(.*\)$/\1/g')
  - MY_IP=$(hostname -I|cut -f1 -d ' ')
  - echo $MY_IP  
  - echo ${mongo_port}
  - docker run --name s3-backup --env AWS_ACCESS_KEY_ID=${aws_access_key} --env INIT_RESTORE=true --env AWS_SECRET_ACCESS_KEY=${aws_secret_key} --env BUCKET=rocketchat-mongodb-backup --env BUCKET_REGION=${aws_region} --env BACKUP_FOLDER=dev/rocketchat_db/ --env MONGODB_HOST=$MY_IP --env MONGODB_PORT=${mongo_port} --env TZ=Europe/Berlin --env CRON_TIME="*/5 * * * *" deenoize/mongodb-backup-s3:latest